shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3 # See https://github.com/paulmillr/chokidar/issues/1440
  - semver@5.7.2 # See https://github.com/npm/node-semver/issues/838
  - undici@6.21.1

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: false
  keytar: false
